### ISSUE TITLE
make library coffeescript friendly

### ISSUE THREAD

**Issue by mreinstein** [bkconrad/wasabi#23]
when I declare this coffeescript class:

``` coffeescript
class Player
    constructor: ->
        @x = 0
        @y = 0
        @owned = false

    serialize: (desc) ->
        desc.uint 'x', 16  # a 16 bit unsigned integer named x
        desc.uint 'y', 16  # a 16 bit unsigned integer named y

    s2cSetControlObject: ->
        @owned = true
```

I get this error at runtime:

```
Error: Attempt to add anonymous RPC. Give it a name with "function NAME () { ... }"
  at Error.WasabiError (/Users/wwwroot/test/node_modules/wasabi/src/wasabi_error.js:2:15)
  at Registry.mkRpc (/Users/wwwroot/test/node_modules/wasabi/src/registry.js:141:19)
  at Registry.addClass (/Users/wwwroot/test/node_modules/wasabi/src/registry.js:115:43)
  at Object.Wasabi.addClass (/Users/wwwroot/test/node_modules/wasabi/src/wasabi.js:57:27)
  at Object.<anonymous> (/Users/wwwroot/test/server.coffee:18:1, <js>:31:10)
  at Object.<anonymous> (/Users/wwwroot/test/server.coffee:1:1, <js>:62:4)
  at Module._compile (module.js:456:26)
```

**Comment by mreinstein** [comment]
btw here is the resulting javascript from the above coffeescript:

``` javascript

Player = (function() {
  function Player() {}

  Player.x = 0;

  Player.y = 0;

  Player.owned = false;

  Player.prototype.serialize = function(desc) {
    desc.uint('x', 16);
    return desc.uint('y', 16);
  };

  Player.prototype.s2cSetControlObject = function() {
    this.owned = true;
    return console.log('very nice');
  };

  return Player;

})();

```

**Comment by mreinstein** [comment]
It seems the problem is coffeescript does not generate named functions. Any suggestions on a workaround? I have a fair amount of code in coffeescript, the idea of having to convert to javascript to wasabi-enable things is kind of a deal breaker. :(

**Comment by bkconrad** [comment]
I believe this is fixed, see my comments on the PR.
