### ISSUE TITLE
bug: scoping fails (causes server crash)

### ISSUE THREAD

**Issue by mreinstein** [bkconrad/wasabi#26]
stack trace from server output:

```
/Users/wwwroot/test/node_modules/wasabi/src/wasabi.js:225
            bs.writeUInt(this.registry.hash(obj.constructor), 16);
                                               ^
TypeError: Cannot read property 'constructor' of undefined
  at Object.Wasabi._packGhost (/Users/wwwroot/test/node_modules/wasabi/src/wasabi.js:225:48)
  at Object.Wasabi._packGhosts (/Users/wwwroot/test/node_modules/wasabi/src/wasabi.js:283:26)
  at Object.Wasabi._processConnection (/Users/wwwroot/test/node_modules/wasabi/src/wasabi.js:605:22)
  at Object.Wasabi.processConnections (/Users/wwwroot/test/node_modules/wasabi/src/wasabi.js:184:26)
  at [object Object].simLoop (/Users/wwwroot/test/server.coffee:61:2, <js>:71:19)
  at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

ship:

``` coffeescript
class Ship
    constructor: ->
        @id = 0
        @zoneId = 0

    serialize: (desc) ->
        desc.uint 'id', 16  # 16 bit unsigned int
        desc.uint 'zoneId', 16

    s2cSetControlObject: ->
        @owned = true

module.exports = Ship
```

server:

``` coffeescript
Wasabi    = require 'wasabi'
WebSocket = require 'ws'
Ship      = require './coffee/ship'

Wasabi.addClass Ship

serverSock = new WebSocket.Server {port:1234}, ->
    setInterval simLoop, (1000/15)  # run the simulation at 15fps

serverSock.on 'connection', (clientSock) ->
    console.log 'got a client connection'
    newShip = new Ship()
    conn = Wasabi.addClient clientSock, () ->
        results = []
        for id, ship of ships
            if (ship.wsbSerialNumber isnt newShip.wsbSerialNumber) and (ship.zoneId is newShip.zoneId)
                results.push ship
        results

    ships[newShip.wsbSerialNumber] = newShip

    Wasabi.addObject newShip

    # add the player to our player list
    conn.player = newShip

    newShip.s2cSetControlObject conn

simLoop = ->
    Wasabi.processConnections()

# convenience data structures to access objects by their id
ships = {}
```

client:

``` coffeescript
Wasabi    = require 'wasabi'
WebSocket = require 'ws'
Ship      = require './coffee/ship'

# convenience data structure to access ships by their id
ships = {}

Wasabi.on 'clientGhostCreate', (obj) ->
    if obj instanceof Ship
        obj.id = obj.wsbSerialNumber
        ships[obj.wsbSerialNumber] = obj
        console.log 'ship created', obj.id

Wasabi.on 'sendError', (conn, er) ->
    console.log 'lost connection to server', er
    ships = {}

sock = new WebSocket 'ws://localhost:1234'

sock.onopen = () ->
    Wasabi.addServer sock
    console.log 'connected to server'
    setInterval simLoop, (1000/15)  # run the simulation at 15fps

simLoop = ->
    #for id, ship of ships
    #   console.log 'ship id', id, 'owner?', ship.owned
    Wasabi.processConnections()
```

**Comment by bkconrad** [comment]
oops, sorry about that. should be fixed now.

**Comment by mreinstein** [comment]
@kaen it's definitely better, the server crash is gone. I'm having a different problem now though.

Here's the code in my server to do scoping:

``` coffeescript
serverSock.on 'connection', (clientSock) ->
    console.log 'got a client connection'
    newShip = new Ship()
    conn = Wasabi.addClient clientSock, ->
        results = []
        for id, ship of ships
            isMe = ship.wsbSerialNumber is @player.wsbSerialNumber
            inZone = ship.zoneId is @player.zoneId
            if isMe or inZone then results.push(ship)
        results

    ships[newShip.wsbSerialNumber] = newShip

    Wasabi.addObject newShip
    # add the player to our player list
    conn.player = newShip
    newShip.s2cSetControlObject conn
```

here's what I see in the console when the 2nd client connects to the server:

```
Uncaught Error: Received update for unknown object 2
```

it seems to be thrown from here

``` javascript
_unpackUpdate: function (bs) {
            var serial = bs.readUInt(16);
            var obj = this.registry.getObject(serial);
            if (!obj) {
                throw new WasabiError('Received update for unknown object ' + serial);
```

**Comment by mreinstein** [comment]
maybe this isn't a bug in your library and I'm simply using the feature wrong? What I'm trying to do is make it so only objects in the client's zone are visible, and changing a client object's zone will change it's visibility. Help! :)

**Comment by bkconrad** [comment]
Reading through your code, it looks totally correct, and I haven't been able to write a test case to duplicate that error. However, it seems that I broke the scoping mechanism in a recent commit. Could you please try:

``` coffeescript
    conn = Wasabi.addClient clientSock, ->
        results = {}
        for id, ship of ships
            isMe = ship.wsbSerialNumber is @player.wsbSerialNumber
            inZone = ship.zoneId is @player.zoneId
            if isMe or inZone then results[ship.wsbSerialNumber] = ship
        results
```

(using an object instead of an array)

If that works, then I believe I have a fix for using an Array.

I'm trying to make Wasabi throw useful errors if there's a bug in user code, so a useless error like this is always my bug :)

**Comment by bkconrad** [comment]
I've pushed an experimental fix to the `arrayfix` branch @cb821acfceb1a94f984100d5a91c540d54eb1ffc

**Comment by mreinstein** [comment]
@kaen I tried using an object instead of an array for the results object in the scope function as you suggested. I get a different problem. The crashing stops, but now the first ship is destroyed. In other words
1 start server
2 start client 1
3 start client 2
   _at this point server disconnects client 1_

I haven't tried the expirimental fix yet. Should I try that now? Should I share the generated javascript so you can reproduce the issue yourself? 

thanks for your help!

**Comment by bkconrad** [comment]
If you would try the fix that would be great, but I suspect it won't help since the object method did not.

If you are willing to share the JavaScript, I'd be happy to debug the issue through that.

Thank you likewise for your help.

**Comment by mreinstein** [comment]
@kaen actually if you're thinking about adding a grouping capability like we talked about, I could just wait for that. Right now I don't absolutely need this functionality. If you want to debug it I'm happy to send over javascript though.

**Comment by bkconrad** [comment]
Added the group functionality request in #21, hopefully that helps
